language: cpp

env: 
  - BUILD_CONFIGURATION=Debug
  - BUILD_CONFIGURATION=Release

os: 
  - linux
  - osx
  - windows

dist: xenial

osx_image: xcode11.4

install:
  - .travis/install.sh

script:
  - .travis/lint.sh
  - .travis/configure.sh
  - .travis/build.sh
