language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.1


before_install:
  - . .travis/before-install.sh

install:
  - . .travis/install.sh

script:
  - . .travis/lint.sh
  - mkdir build
  - cd build
  - cmake ../
  - make
