language: cpp

env: 
  - BUILD_CONFIGURATION=Debug
  - BUILD_CONFIGURATION=Release

os: 
  - linux
  - osx
  - windows

dist: xenial

osx_image: xcode9.1

install:
  - . .travis/install.sh
  - curl -o cpplint.py https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py

script:
  - . .travis/lint.sh
  - mkdir build
  - cd build
  - . ../.travis/build.sh
